---
name: Akhil Sadam
position: "Undergraduate in Computational Engineering, University of Texas at Austin"
address: "2826 Cool River Loop, Round Rock, TX 78665"
profilepic: ./fonts/0.jpg
www: akhilsadam.github.io
github: akhilsadam
linkedin: akhil-sadam
email: akhil.sadam@utexas.edu
phone: 512-298-0307
aboutme: simulation architect / automation engineer, independent game developer and composer. \linebreak \ \ \ \linebreak \ \ \ [\faIcon{buffer} \ research](https://akhilsadam.github.io/projects/research/) \ - \ [\faUnity \ game](https://akhilsadam.github.io/projects/simulation/) \ - \ [\faCubes \  arch-vis](https://akhilsadam.github.io/projects/archvis/) \ - \ [\faImage \ art](https://akhilsadam.github.io/projects/art/) \ - \ [\faCube \ models](https://akhilsadam.github.io/projects/model/) \ - \ [\faIcon{volume-off} \  music](https://akhilsadam.github.io/projects/music/)
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "274175"
docname: curriculum vitae
output:
  vitae::awesomecv:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
library(vitae)
library(here)
library(vroom)
library(dplyr)
library(lubridate)
library(glue)
library(scholar)
```

```{r setup2, include=FALSE}
here::here()
getwd()
here::i_am(path="_.R")
here::here()
```


# Research
```{r child = '../data/positions.md'}
```

# Recent Publications

```{r}
a <- get_publications('6G9FVRgAAAAJ')
year <- a['year']
title <- a['title']
journal <- a['journal']
a2 = a[order(year,journal,title),]
a2[1:5,] |>
  detailed_entries(
    what = title,
    with = author,
    where = journal,
    when = year
  )
```

A complete listing is available [here](https://scholar.google.com/citations?user=6G9FVRgAAAAJ).  

# Skills

```{r}
skills <- vroom(here::here("data", "skills.csv")) |>
  group_by(category) |>
  mutate(skill = paste(skill, collapse = ", ")) |>
  ungroup() |>
  unique()

skills |>
  detailed_entries(what = skill, with = category)
```

# Experience  
```{r child = '../data/xp.md'}
```

# Outreach  
```{r child = '../data/reach.md'}
```




# Education

```{r child = '../data/edu.md'}
```

# Honors

```{r child = '../data/hon.md'}
```


# Additional Information  

Work Eligibility:	Eligible to work in the U.S. with no restrictions.