bib:
# py Publications/bib.py
	cp Publications/my_publications.bib ../../../Website/academic-kickstart/
	cd ../../../Website/academic-kickstart/ && sh bibport.sh
resume:
	sh Resume/update.sh

all: bib resume